hubmapconsortium/ccf-asct-reporter

package-lock.json, src/app/tree/tree.service.ts
=> 19 change the text see debug log

package-lock.json, package.json, src/app/app.component.spec.ts, src/app/app.module.ts, src/app/navbar/navbar.component.html, src/app/navbar/navbar.component.ts, src/app/search/search.component.css, src/app/search/search.component.html, src/app/search/search.component.spec.ts, src/app/search/search.component.ts, src/app/select-search/select-search.component.css, src/app/select-search/select-search.component.html, src/app/select-search/select-search.component.spec.ts, src/app/select-search/select-search.component.ts, src/app/services/bimodal.service.ts, src/app/tree/spec/data.ts, src/app/tree/spec/groups/bimodal.ts, src/app/tree/spec/groups/tree.ts, src/app/tree/spec/signals.ts, src/app/tree/tree.component.html, src/app/tree/tree.component.ts, src/app/vis/vis.component.html, src/app/vis/vis.component.ts, tslint.json
This pull request contains the function that enables the user to search for structures
=> Search functionality 

projects/v2/src/app/modules/navbar/navbar.component.scss, projects/v2/src/app/modules/root/root.component.scss, projects/v2/src/styles.scss
1) NavBar Component
2) Root Component
3) Style.scss file
=> Changing px to rem in NavBar, Root Component and style.scss

projects/v2/src/app/modules/navbar/navbar.component.html, projects/v2/src/app/modules/navbar/navbar.component.scss
Changing class name from toobar to toolbar is completed.
=> fix:Class name typo is fixed in Navbar Component

projects/v2/src/app/components/comapre/comapre.component.html, projects/v2/src/app/modules/navbar/navbar.component.scss, projects/v2/src/app/modules/playground/playground.component.html, projects/v2/src/app/modules/search/search.component.scss
Fixed bringing back the legacy styles to matInputs.
=> fix: Adding legacy style to MatInput

projects/v2/src/app/modules/tree/spec/groups/bimodal.ts
Changing label to rdfs:label in node tool tip
=> fix: Changing label to rdfs:label in node tool tip

projects/v2/src/app/components/controls/vis-controls.component.html, projects/v2/src/app/components/controls/vis-controls.component.scss, projects/v2/src/styles.scss, projects/v2/src/theme.scss
Created a new file for custom theme.
=> chore: Custom theme completed

projects/v2/src/app/store/sheet.state.ts
Completed successfully.
If everything is okay, I will remove the commented code.
This code contains, for all organs Visual rendering there is challenge that after the data from the first organ is received the spinner will stop loading and data in the backend will keep on receiving until all the organs data get received. So I solved that using rxjs forkJoin.
Link to the issue: https://github.com/hubmapconsortium/ccf-asct-reporter/issues/97
=> Implemented completely

projects/v2/src/app/components/report/report.component.html, projects/v2/src/app/components/report/report.component.scss, projects/v2/src/app/components/report/report.component.ts, projects/v2/src/app/components/report/report.module.ts, projects/v2/src/app/components/report/report.service.ts, projects/v2/src/app/models/report.model.ts, projects/v2/src/app/models/sheet.model.ts, projects/v2/src/app/models/tree.model.ts, projects/v2/src/app/modules/root/root.component.html, projects/v2/src/app/modules/root/root.component.ts, projects/v2/src/app/modules/tree/tree.functions.ts, projects/v2/src/app/store/sheet.state.ts
Successfully completed creating a organ wise for all organs report when "showall AS" toggle is on.
=> Organ wise counts in all organs report

README.md, projects/v2/src/app/static/config.ts, projects/v2/src/assets/docs/about/README.md
Changed the lung sheet to draft
=> Changed the lung sheet to Draft.

data-miner/src/index.ts, projects/v2/src/app/components/report/report.component.html, projects/v2/src/app/components/report/report.component.ts, projects/v2/src/app/models/bimodal.model.ts, projects/v2/src/app/models/sheet.model.ts, projects/v2/src/app/modules/tree/bimodal.service.ts, projects/v2/src/app/modules/tree/tree.functions.ts
Changed Data miner and Reporter.
=> Modify miner for b types

projects/v2/src/app/components/report/report.component.html, projects/v2/src/app/components/report/report.component.ts, projects/v2/src/app/components/report/report.service.ts, projects/v2/src/app/modules/root/root.component.html, projects/v2/src/app/modules/root/root.component.ts, projects/v2/src/app/store/sheet.state.ts
Counts table for all organs in Report tab.
shows count for all AS even when "show all AS" toggle is off.
=> Counts show when all organs vis is selected in report tab

package-lock.json, package.json, projects/v2/src/app/components/home/home.component.html, projects/v2/src/app/components/home/home.component.scss, projects/v2/src/app/components/home/home.component.ts, projects/v2/src/app/components/home/home.module.ts, projects/v2/src/app/static/home.ts, projects/v2/src/index.html
=> new Video uploaded

projects/v2/src/app/components/report/report.component.ts
added CT ID and BM ID columns.
=> added ID's to the report

projects/v2/src/app/components/report/report.service.ts
Identical biomarkers and new biomarkers columns are reversed as requested.
=> BUG: Comparison feature report has column headers opposite to VIS output 

projects/v2/src/app/components/report/report.service.ts
=> Comparison feature report

projects/v2/src/assets/configuration.json, projects/v2/src/assets/sheet-config.json
configuration and sheet-config json updated with new table locations
=> Tables new location

projects/v2/src/app/components/report/report.component.html, projects/v2/src/app/components/report/report.component.ts, projects/v2/src/app/modules/navbar/navbar.component.html, projects/v2/src/app/modules/root/root.component.html, projects/v2/src/app/modules/root/root.component.ts
=> hide compare and Report tab in PG mode.

projects/v2/src/assets/sheet-config.json
author added a sheet, wrong sheet was deleted
=> update gid for lung v1.3 draft

asctb-api/src/functions/api.functions.ts, asctb-api/src/functions/omap.functions.ts, asctb-api/src/models/api.model.ts, projects/v2/src/app/components/info/info.component.html
=> 694 handle new omap version with new initialcolumn dev

projects/v2/src/app/store/sheet.state.ts, projects/v2/src/assets/omap-sheet-config.json
Add new OMAP tables 8-13
Add revised versions of OMAP tables 1-7
=> Updated omap-sheet-config.json

projects/v2/src/app/modules/root/root.component.ts, projects/v2/src/app/modules/tree/spec/groups/bimodal.ts, projects/v2/src/app/modules/tree/spec/groups/tree.ts
=> increased line size to 5 and exit playground handled gracefully

projects/v2/src/assets/sheet-config.json
added "Draft" to all the viewValue names for new draft tables; had forgotten to add that in that field; double and triple checked through whole list with search; looks complete.
=> added draft to viewValue for drafts

projects/v2/src/assets/sheet-config.json
@bherr2 please review and merge
=> update for HRA release v2.0 and new drafts

projects/v2/src/assets/sheet-config.json
Added all new drafts and v2.1 HRA DO's
=> Added all new drafts and v2.1 HRA DO's
